sudo: required
services:
    - docker
before_install:
    - docker build -t dcaprilfool/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dcaprilfool/react-test npm test

after_success:
    - docker build -t dcaprilfool/multi-client ./client
    - docker build -t dcaprilfool/multi-nginx ./nginx
    - docker build -t dcaprilfool/multi-worker ./worker
    - docker build -t dcaprilfool/multi-server ./server

# Login to DOCKER HUB
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# pushh images to dockerHUB
    - docker push dcaprilfool/multi-client
    - docker push dcaprilfool/multi-server
    - docker push dcaprilfool/multi-nginx
    - docker push dcaprilfool/multi-worker

deploy:
    edge: true
    provider: elasticbeantalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-787472849674
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

