sudo: required
services:
    - docker
before_install:
    - docker build -t dcaprilfool/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dcaprilfool/react-test npm test

after_success:
    - docker build -t dcaprilfool/multi-client ./client
    - docker build -t dcaprilfool/multi-nginx ./nginx
    - docker build -t dcaprilfool/multi-worker ./worker
    - dokcer build -t dcaprilfool/multi-server ./server

# Login to DOCKER HUB
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# pushh images to dockerHUB
    - docker push dcaprilfool/multi-client
    - docker push dcaprilfool/multi-server
    - docker push dcaprilfool/multi-nginx
    - docker push dcaprilfool/multi-work
